/**
 * Analytics Batch Sync API
 * 
 * POST /api/analytics/batch
 * 
 * Nhận batch analytics events từ client (offline sync)
 * và insert vào Supabase
 */

import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@/lib/supabase/server';

interface AnalyticsEvent {
  id?: string;
  poi_id?: string;
  session_id: string;
  rounded_lat?: number;
  rounded_lng?: number;
  language?: string;
  event_type: string;
  listen_duration?: number;
  completed?: boolean;
  user_agent?: string;
  timestamp?: string;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { events } = body as { events: AnalyticsEvent[] };

    if (!events || !Array.isArray(events) || events.length === 0) {
      return NextResponse.json(
        { error: 'No events provided' },
        { status: 400 }
      );
    }

    // Validate events
    const validEvents = events.filter(event => {
      return event.session_id && event.event_type;
    });

    if (validEvents.length === 0) {
      return NextResponse.json(
        { error: 'No valid events' },
        { status: 400 }
      );
    }

    // Transform events to match database schema
    const dbEvents = validEvents.map(event => ({
      poi_id: event.poi_id || null,
      session_id: event.session_id,
      rounded_lat: event.rounded_lat ?? null,
      rounded_lng: event.rounded_lng ?? null,
      language: event.language || null,
      event_type: event.event_type,
      listen_duration: event.listen_duration ?? null,
      completed: event.completed ?? null,
      user_agent: event.user_agent || null,
      // Note: timestamp is auto-generated by database if not provided
    }));

    const supabase = await createServerClient();

    const { data, error } = await supabase
      .from('analytics_logs')
      .insert(dbEvents)
      .select('id');

    if (error) {
      console.error('Failed to batch insert analytics:', error);
      return NextResponse.json(
        { error: 'Failed to sync analytics', details: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      synced: data?.length || validEvents.length,
      message: `Successfully synced ${data?.length || validEvents.length} events`,
    });
  } catch (error) {
    console.error('Analytics batch sync error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * GET /api/analytics/batch
 * 
 * Health check endpoint
 */
export async function GET() {
  return NextResponse.json({
    status: 'ok',
    message: 'Analytics batch sync endpoint ready',
  });
}
